name: Deploy to Render

on:
  push:
    branches:
      - main  # Yahan wo branch likho jisse tum Render pe deploy karti ho

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Notify GitHub: Deployment Started
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1citkadbo4c73ctgu0g?key=mrBTVaFmkVo

      - name: Notify GitHub: Deployment Success
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          status: success